apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sno-0-0-imageset.yaml
  - roles-binding.yaml
configMapGenerator:
  - name: art-image-mirrors
    namespace: sno-0-0
    files:
      - art-image-mirrors.yaml      
generatorOptions:
  disableNameSuffixHash: true
