apiVersion: v1
kind: ConfigMap
metadata:
  name: image-policy-manifests
  namespace: mist08-1
data:
  # The key defines the final manifest file name in the installer directory
  99-cluster-image-policy.yaml: |
    apiVersion: config.openshift.io/v1
    kind: Image
    metadata:
      name: cluster
    spec:
      registrySources:
        # 1. Disable strict container policy / skip TLS for local mirrors
        #insecureRegistries:
          #- "local-registry.internal.net:5000"
          #- "dev-registry.corp:443"
        # 2. Optional: Enforce only specific authorized registries 
        allowedRegistries:
          - "quay.io"
          - "registry.redhat.io"
