apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: art-image-mirrors
spec:
  imageDigestMirrors:
    - mirrors:
      - registry.stage.redhat.io/rhacm2
      source: registry.redhat.io/rhacm2
    - mirrors:
      - registry.stage.redhat.io/multicluster-engine
      source: registry.redhat.io/multicluster-engine
    - mirrors:
      - registry.stage.redhat.io/rh-osbs
      source: registry-proxy.engineering.redhat.com/rh-osbs
    - mirrors:
      - registry.stage.redhat.io/oadp
      source: registry.redhat.io/oadp

              
