apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mist08-1-imageset.yaml
  - roles-binding.yaml
configMapGenerator:
  - name: art-image-mirrors
    namespace: mist08-1
    files:
      - art-image-mirrors.yaml      
generatorOptions:
  disableNameSuffixHash: true
