# example-node[123]-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-3node
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "mist09-0"
  namespace: "mist09-0"
spec:
  baseDomain: "install.dev09.red-chesterfield.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.12.9-multi-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDm9hb6iTZJypEmzg4IZ767ze60UGhBWnjPXhovWVB7uKputdLzZhmlo36ifkXr/DTk8NGm47r6kXmz9NAF0pDHa5jX6yJFnhS4z5NY/mzsUX41gwiqBKYHgdp/KE1ylE8mbNon5ZpaaGvb876myjjPjPwWsD8hvXZirA5Q8TfDb/Pvgy1dhVH/uN05Ip1vVsp+bFGMPUJVWVUy/Eby5xW6OJv+FBOQq4nu6tslDZlHYXX2TSGrlW4x0i/oQMpKu/Y8ygAdjWqmAy6UBcho1nNWy15cp0jI5Fhjze171vSWZLAqJY+eFcL2kt/09RnY+MXyY/tIf+qNMyBE2Qltigah"
  clusters:
  - clusterName: "mist09-0"
    networkType: "OVNKubernetes"
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      #common: true
      # ../policygentemplates/group-du-3node-ranGen.yaml will apply to all clusters with 'group-du-3node: ""'
      #group-du-3node: ""
      # ../policygentemplates/example-multinode-site.yaml will apply to all clusters with 'sites: "example-multinode"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      #sites : "example-multinode"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    # For 3-node and standard clusters with static IPs, the API and Ingress IPs must be configured here
    apiVIP: 192.168.123.5
    ingressVIP: 192.168.123.10
    serviceNetwork:
      - 172.30.0.0/16
    #additionalNTPSources:
    #  - 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    crTemplates:
      KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    # Optionally; This can be used to to configure desired BIOS setting on all nodes in this cluster:
    #biosConfigRef:
    #  filePath: "example-hw.profile"
    nodes:
      - hostName: "master-0-0"
        role: "master"
        bmcAddress: "redfish-virtualmedia://192.168.123.1:8000/redfish/v1/Systems/6dd98dd9-ff69-4f43-b3a1-5bf5e29672a7"
        bmcCredentialsName:
          name: "mist09-0-bmh-secret"
        bootMACAddress: "52:54:00:72:db:56"
        # Use UEFISecureBoot to enable secure boot for this node
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/sda
        nodeNetwork:
          interfaces:
            - name: enp0s4
              macAddress: "52:54:00:72:db:56"
          config:
            interfaces:
              - name: enp0s4
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                    - ip: '192.168.123.118'
                      prefix-length: 24
                  dhcp: false
                # ipv6:
                #   enabled: true
                #   address:
                #   - ip: 1111:2222:3333:4444::aaaa:1
                #     prefix-length: 64
            dns-resolver:
              config:
                server:
                  - '8.8.8.8'
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-address: '192.168.123.1'
                  next-hop-interface: enp0s4
                  table-id: 254                       
      - hostName: "master-0-1"
        role: "master"
        bmcAddress: "redfish-virtualmedia://192.168.123.1:8000/redfish/v1/Systems/87224501-b4a4-4f23-adf8-38de54b33160"
        bmcCredentialsName:
          name: "mist09-0-bmh-secret"
        bootMACAddress: "52:54:00:26:0b:e0"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/sda
        nodeNetwork:
          interfaces:
            - name: enp0s4
              macAddress: "52:54:00:26:0b:e0"
          config:          
            interfaces:
              - name: enp0s4
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                    - ip: '192.168.123.139'
                      prefix-length: 24
                  dhcp: false
            dns-resolver:
              config:
                server:
                  - '8.8.8.8'
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-address: '192.168.123.1'
                  next-hop-interface: enp0s4
                  table-id: 254            
      - hostName: "master-0-2"
        role: "master"
        bmcAddress: "redfish-virtualmedia://192.168.123.1:8000/redfish/v1/Systems/40f0afc5-d494-4ffe-8fc3-a683bf46898f"
        bmcCredentialsName:
          name: "mist09-0-bmh-secret"
        bootMACAddress: "52:54:00:ae:75:d7"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/sda
        nodeNetwork:
          interfaces:
            - name: enp0s4
              macAddress: "52:54:00:ae:75:d7"
          config:             
            interfaces:
              - name: enp0s4
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                    - ip: '192.168.123.132'
                      prefix-length: 24
                  dhcp: false
            dns-resolver:
              config:
                server:
                  - '8.8.8.8'
            routes:
              config:
                - destination: 0.0.0.0/0
                  next-hop-address: '192.168.123.1'
                  next-hop-interface: enp0s4
                  table-id: 254                   