# example-node[123]-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-3node
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "worker-1-0"
  namespace: "worker-1-0"
spec:
  baseDomain: "qe.red-chesterfield.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.13.24-multi-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDm9hb6iTZJypEmzg4IZ767ze60UGhBWnjPXhovWVB7uKputdLzZhmlo36ifkXr/DTk8NGm47r6kXmz9NAF0pDHa5jX6yJFnhS4z5NY/mzsUX41gwiqBKYHgdp/KE1ylE8mbNon5ZpaaGvb876myjjPjPwWsD8hvXZirA5Q8TfDb/Pvgy1dhVH/uN05Ip1vVsp+bFGMPUJVWVUy/Eby5xW6OJv+FBOQq4nu6tslDZlHYXX2TSGrlW4x0i/oQMpKu/Y8ygAdjWqmAy6UBcho1nNWy15cp0jI5Fhjze171vSWZLAqJY+eFcL2kt/09RnY+MXyY/tIf+qNMyBE2Qltigah"
  clusters:
  - clusterName: "worker-1-0"
    networkType: "OVNKubernetes"
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      #common: true
      # ../policygentemplates/group-du-3node-ranGen.yaml will apply to all clusters with 'group-du-3node: ""'
      #group-du-3node: ""
      # ../policygentemplates/example-multinode-site.yaml will apply to all clusters with 'sites: "example-multinode"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      #sites : "example-multinode"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.124.0/24         
    serviceNetwork:
      - 172.30.0.0/16
    #additionalNTPSources:
    #  - 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    crTemplates:
      KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    # Optionally; This can be used to to configure desired BIOS setting on all nodes in this cluster:
    #biosConfigRef:
    #  filePath: "example-hw.profile"
    nodes:
      - hostName: "worker-1-0"
        role: "master"
        bmcAddress: "redfish-virtualmedia://192.168.123.1:8000/redfish/v1/Systems/60b130f1-ed28-4ddf-b149-33e00baa806e"
        bmcCredentialsName:
          name: "worker-1-0-bmh-secret"
        bootMACAddress: "52:54:00:f2:f2:90"
        # Use UEFISecureBoot to enable secure boot for this node
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: /dev/sda
        # nodeNetwork:
        #   interfaces:
        #     - name: enp0s4
        #       macAddress: "52:54:00:72:db:56"
        #   config:
        #     interfaces:
        #       - name: enp0s4
        #         type: ethernet
        #         state: up
        #         ipv4:
        #           enabled: true
        #           address:
        #             - ip: '192.168.123.118'
        #               prefix-length: 24
        #           # dhcp: false
        #         ipv6:
        #           enabled: false
        #         #   address:
        #         #   - ip: 1111:2222:3333:4444::aaaa:1
        #         #     prefix-length: 64
        #     routes:
        #       config:
        #         - destination: 0.0.0.0/0
        #           next-hop-address: '192.168.123.1'
        #           next-hop-interface: enp0s4
        #           table-id: 254         
